# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      # logs into gh pkg registry
      - name: login to gh
        run: |
          docker login docker.pkg.github.com -u "$UNAME" -p "$TOKEN"
        env:
          TOKEN: ${{ secrets.TOKEN_GH }}
          UNAME: ${{ secrets.UNAME }}


      # build docker image
      - name: build docker image
        run: |
          docker build . -t discord-math-bot:latest

      # tag docker image
      - name: tag docker image
        run: |
          docker tag discord-math-bot:latest docker.pkg.github.com/hello512/discord-math-bot/discord-math-bot:latest

      # push docker image
      - name: push docker image
        run: |
          docker push docker.pkg.github.com/hello512/discord-math-bot/discord-math-bot:latest
          
      - name: logout from docker
        run: |
          docker logout
          
      - name: login to docker
        run: |
          run docker login -u DOCKER_USER -p DOCKER_TOKEN
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          
      - name: untag docker image
        run: |
          docker rmi docker.pkg.github.com/hello512/discord-math-bot/discord-math-bot:latest
          
      - name: tag docker image
        run: |
          docker tag discord-math-bot:latest hello512/discord-math-bot:latest
          
      - name: push image
        run: |
          docker push hello512/discord-math-bot:latest
                    
